### ISSUE TITLE
Melhoria no HTML na página do produto

### ISSUE THREAD

**Issue by Thomazrlima** [P-E-N-T-E-S/Kolekto#23]
O produto ainda aparece de forma estranha. centralizada na página da loja
![image](https://github.com/P-E-N-T-E-S/Kolekto/assets/126795323/b045ed49-8716-4ba1-944e-fadc4358fe97)

**Comment by hsspedro** [comment]
Produtos formatados.

**Comment by hsspedro** [comment]
Produtos formatados.
