### ISSUE TITLE
Tratar os erros de adicionar produtos

### ISSUE THREAD

**Issue by Thomazrlima** [P-E-N-T-E-S/Kolekto#28]
Ao adicionar um valor muito grande uma string o programa quebra

![Image](https://github.com/P-E-N-T-E-S/Kolekto/assets/126795323/3de31fbe-2032-4a0b-9d47-fc25889073d3)

**Comment by Sofia-Saraiva** [comment]
Fizemos tratamento de erro quando o preco recebe string e mudamos o input de quantidade para apenas receber int

**Comment by Sofia-Saraiva** [comment]
Fizemos tratamento de erro quando o preco recebe string e mudamos o input de quantidade para apenas receber int
